# Site settings
title: CoderDojo Kapfenberg
email: info@coderdojo-kapfenberg.org
description: > # this means to ignore newlines until "baseurl:"
  Die CoderDojo Gemeinschaft organisiert Programmierclubs für Kinder und Jugendliche zwischen 8 und 18 Jahren. Diese Seite ist für die CoderDojos Kapfenberg.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coderdojo-kapfenberg.github.io" # the base hostname & protocol for your site
twitter_username: ByteDoc
github_username:  CoderDojo-Kapfenberg

# Build settings
markdown: kramdown

exclude: ["bin", "bower_components", "jekyll", "node_modules", "obj", "styles/sass/*.*", "typings", "coderdojo-linz.*", "*.json", "app.*", "Gulpfile.js"]
